// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plamgortti.txt

package com.evialab.the3rd;

public final class PlamgoRTTI {
  private PlamgoRTTI() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LinkTrafficInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DTIPlus.LinkTrafficInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 linkid = 1;</code>
     *
     * <pre>
     * 单个网格内id
     * </pre>
     */
    boolean hasLinkid();
    /**
     * <code>required int32 linkid = 1;</code>
     *
     * <pre>
     * 单个网格内id
     * </pre>
     */
    int getLinkid();

    /**
     * <code>required int32 trafficInfo = 2;</code>
     *
     * <pre>
     * 由左至右依次表示 正向速度�?9bit,int），正向等级�?3bit,int�?,预留 �?4bit），反向速度�?9bit,int），反向等级�?3bit,int），预留 �?4bit�?
     * </pre>
     */
    boolean hasTrafficInfo();
    /**
     * <code>required int32 trafficInfo = 2;</code>
     *
     * <pre>
     * 由左至右依次表示 正向速度�?9bit,int），正向等级�?3bit,int�?,预留 �?4bit），反向速度�?9bit,int），反向等级�?3bit,int），预留 �?4bit�?
     * </pre>
     */
    int getTrafficInfo();
  }
  /**
   * Protobuf type {@code DTIPlus.LinkTrafficInfo}
   */
  public static final class LinkTrafficInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DTIPlus.LinkTrafficInfo)
      LinkTrafficInfoOrBuilder {
    // Use LinkTrafficInfo.newBuilder() to construct.
    private LinkTrafficInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LinkTrafficInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LinkTrafficInfo defaultInstance;
    public static LinkTrafficInfo getDefaultInstance() {
      return defaultInstance;
    }

    public LinkTrafficInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LinkTrafficInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              linkid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              trafficInfo_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.evialab.the3rd.PlamgoRTTI.internal_static_DTIPlus_LinkTrafficInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.evialab.the3rd.PlamgoRTTI.internal_static_DTIPlus_LinkTrafficInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.class, com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<LinkTrafficInfo> PARSER =
        new com.google.protobuf.AbstractParser<LinkTrafficInfo>() {
      public LinkTrafficInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LinkTrafficInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LinkTrafficInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LINKID_FIELD_NUMBER = 1;
    private int linkid_;
    /**
     * <code>required int32 linkid = 1;</code>
     *
     * <pre>
     * 单个网格内id
     * </pre>
     */
    public boolean hasLinkid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 linkid = 1;</code>
     *
     * <pre>
     * 单个网格内id
     * </pre>
     */
    public int getLinkid() {
      return linkid_;
    }

    public static final int TRAFFICINFO_FIELD_NUMBER = 2;
    private int trafficInfo_;
    /**
     * <code>required int32 trafficInfo = 2;</code>
     *
     * <pre>
     * 由左至右依次表示 正向速度�?9bit,int），正向等级�?3bit,int�?,预留 �?4bit），反向速度�?9bit,int），反向等级�?3bit,int），预留 �?4bit�?
     * </pre>
     */
    public boolean hasTrafficInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 trafficInfo = 2;</code>
     *
     * <pre>
     * 由左至右依次表示 正向速度�?9bit,int），正向等级�?3bit,int�?,预留 �?4bit），反向速度�?9bit,int），反向等级�?3bit,int），预留 �?4bit�?
     * </pre>
     */
    public int getTrafficInfo() {
      return trafficInfo_;
    }

    private void initFields() {
      linkid_ = 0;
      trafficInfo_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLinkid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTrafficInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, linkid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, trafficInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, linkid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, trafficInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DTIPlus.LinkTrafficInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DTIPlus.LinkTrafficInfo)
        com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.evialab.the3rd.PlamgoRTTI.internal_static_DTIPlus_LinkTrafficInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.evialab.the3rd.PlamgoRTTI.internal_static_DTIPlus_LinkTrafficInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.class, com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.Builder.class);
      }

      // Construct using com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        linkid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        trafficInfo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.evialab.the3rd.PlamgoRTTI.internal_static_DTIPlus_LinkTrafficInfo_descriptor;
      }

      public com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo getDefaultInstanceForType() {
        return com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.getDefaultInstance();
      }

      public com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo build() {
        com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo buildPartial() {
        com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo result = new com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.linkid_ = linkid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.trafficInfo_ = trafficInfo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo) {
          return mergeFrom((com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo other) {
        if (other == com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.getDefaultInstance()) return this;
        if (other.hasLinkid()) {
          setLinkid(other.getLinkid());
        }
        if (other.hasTrafficInfo()) {
          setTrafficInfo(other.getTrafficInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLinkid()) {
          
          return false;
        }
        if (!hasTrafficInfo()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int linkid_ ;
      /**
       * <code>required int32 linkid = 1;</code>
       *
       * <pre>
       * 单个网格内id
       * </pre>
       */
      public boolean hasLinkid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 linkid = 1;</code>
       *
       * <pre>
       * 单个网格内id
       * </pre>
       */
      public int getLinkid() {
        return linkid_;
      }
      /**
       * <code>required int32 linkid = 1;</code>
       *
       * <pre>
       * 单个网格内id
       * </pre>
       */
      public Builder setLinkid(int value) {
        bitField0_ |= 0x00000001;
        linkid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 linkid = 1;</code>
       *
       * <pre>
       * 单个网格内id
       * </pre>
       */
      public Builder clearLinkid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        linkid_ = 0;
        onChanged();
        return this;
      }

      private int trafficInfo_ ;
      /**
       * <code>required int32 trafficInfo = 2;</code>
       *
       * <pre>
       * 由左至右依次表示 正向速度�?9bit,int），正向等级�?3bit,int�?,预留 �?4bit），反向速度�?9bit,int），反向等级�?3bit,int），预留 �?4bit�?
       * </pre>
       */
      public boolean hasTrafficInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 trafficInfo = 2;</code>
       *
       * <pre>
       * 由左至右依次表示 正向速度�?9bit,int），正向等级�?3bit,int�?,预留 �?4bit），反向速度�?9bit,int），反向等级�?3bit,int），预留 �?4bit�?
       * </pre>
       */
      public int getTrafficInfo() {
        return trafficInfo_;
      }
      /**
       * <code>required int32 trafficInfo = 2;</code>
       *
       * <pre>
       * 由左至右依次表示 正向速度�?9bit,int），正向等级�?3bit,int�?,预留 �?4bit），反向速度�?9bit,int），反向等级�?3bit,int），预留 �?4bit�?
       * </pre>
       */
      public Builder setTrafficInfo(int value) {
        bitField0_ |= 0x00000002;
        trafficInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 trafficInfo = 2;</code>
       *
       * <pre>
       * 由左至右依次表示 正向速度�?9bit,int），正向等级�?3bit,int�?,预留 �?4bit），反向速度�?9bit,int），反向等级�?3bit,int），预留 �?4bit�?
       * </pre>
       */
      public Builder clearTrafficInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        trafficInfo_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DTIPlus.LinkTrafficInfo)
    }

    static {
      defaultInstance = new LinkTrafficInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DTIPlus.LinkTrafficInfo)
  }

  public interface MeshTrafficInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DTIPlus.MeshTrafficInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 meshid = 1;</code>
     *
     * <pre>
     * 网格�?
     * </pre>
     */
    boolean hasMeshid();
    /**
     * <code>required int32 meshid = 1;</code>
     *
     * <pre>
     * 网格�?
     * </pre>
     */
    int getMeshid();

    /**
     * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
     */
    java.util.List<com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo> 
        getLinkTrafficInfoList();
    /**
     * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
     */
    com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo getLinkTrafficInfo(int index);
    /**
     * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
     */
    int getLinkTrafficInfoCount();
    /**
     * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
     */
    java.util.List<? extends com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfoOrBuilder> 
        getLinkTrafficInfoOrBuilderList();
    /**
     * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
     */
    com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfoOrBuilder getLinkTrafficInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DTIPlus.MeshTrafficInfo}
   */
  public static final class MeshTrafficInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DTIPlus.MeshTrafficInfo)
      MeshTrafficInfoOrBuilder {
    // Use MeshTrafficInfo.newBuilder() to construct.
    private MeshTrafficInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MeshTrafficInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MeshTrafficInfo defaultInstance;
    public static MeshTrafficInfo getDefaultInstance() {
      return defaultInstance;
    }

    public MeshTrafficInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MeshTrafficInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              meshid_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                linkTrafficInfo_ = new java.util.ArrayList<com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              linkTrafficInfo_.add(input.readMessage(com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          linkTrafficInfo_ = java.util.Collections.unmodifiableList(linkTrafficInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.evialab.the3rd.PlamgoRTTI.internal_static_DTIPlus_MeshTrafficInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.evialab.the3rd.PlamgoRTTI.internal_static_DTIPlus_MeshTrafficInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.class, com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<MeshTrafficInfo> PARSER =
        new com.google.protobuf.AbstractParser<MeshTrafficInfo>() {
      public MeshTrafficInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MeshTrafficInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MeshTrafficInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MESHID_FIELD_NUMBER = 1;
    private int meshid_;
    /**
     * <code>required int32 meshid = 1;</code>
     *
     * <pre>
     * 网格�?
     * </pre>
     */
    public boolean hasMeshid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 meshid = 1;</code>
     *
     * <pre>
     * 网格�?
     * </pre>
     */
    public int getMeshid() {
      return meshid_;
    }

    public static final int LINKTRAFFICINFO_FIELD_NUMBER = 2;
    private java.util.List<com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo> linkTrafficInfo_;
    /**
     * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
     */
    public java.util.List<com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo> getLinkTrafficInfoList() {
      return linkTrafficInfo_;
    }
    /**
     * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
     */
    public java.util.List<? extends com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfoOrBuilder> 
        getLinkTrafficInfoOrBuilderList() {
      return linkTrafficInfo_;
    }
    /**
     * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
     */
    public int getLinkTrafficInfoCount() {
      return linkTrafficInfo_.size();
    }
    /**
     * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
     */
    public com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo getLinkTrafficInfo(int index) {
      return linkTrafficInfo_.get(index);
    }
    /**
     * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
     */
    public com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfoOrBuilder getLinkTrafficInfoOrBuilder(
        int index) {
      return linkTrafficInfo_.get(index);
    }

    private void initFields() {
      meshid_ = 0;
      linkTrafficInfo_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMeshid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getLinkTrafficInfoCount(); i++) {
        if (!getLinkTrafficInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, meshid_);
      }
      for (int i = 0; i < linkTrafficInfo_.size(); i++) {
        output.writeMessage(2, linkTrafficInfo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, meshid_);
      }
      for (int i = 0; i < linkTrafficInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, linkTrafficInfo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DTIPlus.MeshTrafficInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DTIPlus.MeshTrafficInfo)
        com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.evialab.the3rd.PlamgoRTTI.internal_static_DTIPlus_MeshTrafficInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.evialab.the3rd.PlamgoRTTI.internal_static_DTIPlus_MeshTrafficInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.class, com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.Builder.class);
      }

      // Construct using com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLinkTrafficInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        meshid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (linkTrafficInfoBuilder_ == null) {
          linkTrafficInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          linkTrafficInfoBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.evialab.the3rd.PlamgoRTTI.internal_static_DTIPlus_MeshTrafficInfo_descriptor;
      }

      public com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo getDefaultInstanceForType() {
        return com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.getDefaultInstance();
      }

      public com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo build() {
        com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo buildPartial() {
        com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo result = new com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.meshid_ = meshid_;
        if (linkTrafficInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            linkTrafficInfo_ = java.util.Collections.unmodifiableList(linkTrafficInfo_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.linkTrafficInfo_ = linkTrafficInfo_;
        } else {
          result.linkTrafficInfo_ = linkTrafficInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo) {
          return mergeFrom((com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo other) {
        if (other == com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.getDefaultInstance()) return this;
        if (other.hasMeshid()) {
          setMeshid(other.getMeshid());
        }
        if (linkTrafficInfoBuilder_ == null) {
          if (!other.linkTrafficInfo_.isEmpty()) {
            if (linkTrafficInfo_.isEmpty()) {
              linkTrafficInfo_ = other.linkTrafficInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureLinkTrafficInfoIsMutable();
              linkTrafficInfo_.addAll(other.linkTrafficInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.linkTrafficInfo_.isEmpty()) {
            if (linkTrafficInfoBuilder_.isEmpty()) {
              linkTrafficInfoBuilder_.dispose();
              linkTrafficInfoBuilder_ = null;
              linkTrafficInfo_ = other.linkTrafficInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
              linkTrafficInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLinkTrafficInfoFieldBuilder() : null;
            } else {
              linkTrafficInfoBuilder_.addAllMessages(other.linkTrafficInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMeshid()) {
          
          return false;
        }
        for (int i = 0; i < getLinkTrafficInfoCount(); i++) {
          if (!getLinkTrafficInfo(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int meshid_ ;
      /**
       * <code>required int32 meshid = 1;</code>
       *
       * <pre>
       * 网格�?
       * </pre>
       */
      public boolean hasMeshid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 meshid = 1;</code>
       *
       * <pre>
       * 网格�?
       * </pre>
       */
      public int getMeshid() {
        return meshid_;
      }
      /**
       * <code>required int32 meshid = 1;</code>
       *
       * <pre>
       * 网格�?
       * </pre>
       */
      public Builder setMeshid(int value) {
        bitField0_ |= 0x00000001;
        meshid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 meshid = 1;</code>
       *
       * <pre>
       * 网格�?
       * </pre>
       */
      public Builder clearMeshid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        meshid_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo> linkTrafficInfo_ =
        java.util.Collections.emptyList();
      private void ensureLinkTrafficInfoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          linkTrafficInfo_ = new java.util.ArrayList<com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo>(linkTrafficInfo_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo, com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.Builder, com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfoOrBuilder> linkTrafficInfoBuilder_;

      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public java.util.List<com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo> getLinkTrafficInfoList() {
        if (linkTrafficInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(linkTrafficInfo_);
        } else {
          return linkTrafficInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public int getLinkTrafficInfoCount() {
        if (linkTrafficInfoBuilder_ == null) {
          return linkTrafficInfo_.size();
        } else {
          return linkTrafficInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo getLinkTrafficInfo(int index) {
        if (linkTrafficInfoBuilder_ == null) {
          return linkTrafficInfo_.get(index);
        } else {
          return linkTrafficInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public Builder setLinkTrafficInfo(
          int index, com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo value) {
        if (linkTrafficInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinkTrafficInfoIsMutable();
          linkTrafficInfo_.set(index, value);
          onChanged();
        } else {
          linkTrafficInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public Builder setLinkTrafficInfo(
          int index, com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.Builder builderForValue) {
        if (linkTrafficInfoBuilder_ == null) {
          ensureLinkTrafficInfoIsMutable();
          linkTrafficInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          linkTrafficInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public Builder addLinkTrafficInfo(com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo value) {
        if (linkTrafficInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinkTrafficInfoIsMutable();
          linkTrafficInfo_.add(value);
          onChanged();
        } else {
          linkTrafficInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public Builder addLinkTrafficInfo(
          int index, com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo value) {
        if (linkTrafficInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinkTrafficInfoIsMutable();
          linkTrafficInfo_.add(index, value);
          onChanged();
        } else {
          linkTrafficInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public Builder addLinkTrafficInfo(
          com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.Builder builderForValue) {
        if (linkTrafficInfoBuilder_ == null) {
          ensureLinkTrafficInfoIsMutable();
          linkTrafficInfo_.add(builderForValue.build());
          onChanged();
        } else {
          linkTrafficInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public Builder addLinkTrafficInfo(
          int index, com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.Builder builderForValue) {
        if (linkTrafficInfoBuilder_ == null) {
          ensureLinkTrafficInfoIsMutable();
          linkTrafficInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          linkTrafficInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public Builder addAllLinkTrafficInfo(
          java.lang.Iterable<? extends com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo> values) {
        if (linkTrafficInfoBuilder_ == null) {
          ensureLinkTrafficInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, linkTrafficInfo_);
          onChanged();
        } else {
          linkTrafficInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public Builder clearLinkTrafficInfo() {
        if (linkTrafficInfoBuilder_ == null) {
          linkTrafficInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          linkTrafficInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public Builder removeLinkTrafficInfo(int index) {
        if (linkTrafficInfoBuilder_ == null) {
          ensureLinkTrafficInfoIsMutable();
          linkTrafficInfo_.remove(index);
          onChanged();
        } else {
          linkTrafficInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.Builder getLinkTrafficInfoBuilder(
          int index) {
        return getLinkTrafficInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfoOrBuilder getLinkTrafficInfoOrBuilder(
          int index) {
        if (linkTrafficInfoBuilder_ == null) {
          return linkTrafficInfo_.get(index);  } else {
          return linkTrafficInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public java.util.List<? extends com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfoOrBuilder> 
           getLinkTrafficInfoOrBuilderList() {
        if (linkTrafficInfoBuilder_ != null) {
          return linkTrafficInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(linkTrafficInfo_);
        }
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.Builder addLinkTrafficInfoBuilder() {
        return getLinkTrafficInfoFieldBuilder().addBuilder(
            com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.Builder addLinkTrafficInfoBuilder(
          int index) {
        return getLinkTrafficInfoFieldBuilder().addBuilder(
            index, com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .DTIPlus.LinkTrafficInfo linkTrafficInfo = 2;</code>
       */
      public java.util.List<com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.Builder> 
           getLinkTrafficInfoBuilderList() {
        return getLinkTrafficInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo, com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.Builder, com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfoOrBuilder> 
          getLinkTrafficInfoFieldBuilder() {
        if (linkTrafficInfoBuilder_ == null) {
          linkTrafficInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo, com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfo.Builder, com.evialab.the3rd.PlamgoRTTI.LinkTrafficInfoOrBuilder>(
                  linkTrafficInfo_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          linkTrafficInfo_ = null;
        }
        return linkTrafficInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:DTIPlus.MeshTrafficInfo)
    }

    static {
      defaultInstance = new MeshTrafficInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DTIPlus.MeshTrafficInfo)
  }

  public interface TrafficInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DTIPlus.TrafficInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string head = 1;</code>
     *
     * <pre>
     * json字符�? type（rh/fcd）�?�version
     * </pre>
     */
    boolean hasHead();
    /**
     * <code>required string head = 1;</code>
     *
     * <pre>
     * json字符�? type（rh/fcd）�?�version
     * </pre>
     */
    java.lang.String getHead();
    /**
     * <code>required string head = 1;</code>
     *
     * <pre>
     * json字符�? type（rh/fcd）�?�version
     * </pre>
     */
    com.google.protobuf.ByteString
        getHeadBytes();

    /**
     * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
     */
    java.util.List<com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo> 
        getMeshTrafficInfoList();
    /**
     * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
     */
    com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo getMeshTrafficInfo(int index);
    /**
     * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
     */
    int getMeshTrafficInfoCount();
    /**
     * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
     */
    java.util.List<? extends com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfoOrBuilder> 
        getMeshTrafficInfoOrBuilderList();
    /**
     * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
     */
    com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfoOrBuilder getMeshTrafficInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DTIPlus.TrafficInfo}
   */
  public static final class TrafficInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DTIPlus.TrafficInfo)
      TrafficInfoOrBuilder {
    // Use TrafficInfo.newBuilder() to construct.
    private TrafficInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TrafficInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TrafficInfo defaultInstance;
    public static TrafficInfo getDefaultInstance() {
      return defaultInstance;
    }

    public TrafficInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TrafficInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              head_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                meshTrafficInfo_ = new java.util.ArrayList<com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              meshTrafficInfo_.add(input.readMessage(com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          meshTrafficInfo_ = java.util.Collections.unmodifiableList(meshTrafficInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.evialab.the3rd.PlamgoRTTI.internal_static_DTIPlus_TrafficInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.evialab.the3rd.PlamgoRTTI.internal_static_DTIPlus_TrafficInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.evialab.the3rd.PlamgoRTTI.TrafficInfo.class, com.evialab.the3rd.PlamgoRTTI.TrafficInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<TrafficInfo> PARSER =
        new com.google.protobuf.AbstractParser<TrafficInfo>() {
      public TrafficInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TrafficInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TrafficInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HEAD_FIELD_NUMBER = 1;
    private java.lang.Object head_;
    /**
     * <code>required string head = 1;</code>
     *
     * <pre>
     * json字符�? type（rh/fcd）�?�version
     * </pre>
     */
    public boolean hasHead() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string head = 1;</code>
     *
     * <pre>
     * json字符�? type（rh/fcd）�?�version
     * </pre>
     */
    public java.lang.String getHead() {
      java.lang.Object ref = head_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          head_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string head = 1;</code>
     *
     * <pre>
     * json字符�? type（rh/fcd）�?�version
     * </pre>
     */
    public com.google.protobuf.ByteString
        getHeadBytes() {
      java.lang.Object ref = head_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        head_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESHTRAFFICINFO_FIELD_NUMBER = 2;
    private java.util.List<com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo> meshTrafficInfo_;
    /**
     * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
     */
    public java.util.List<com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo> getMeshTrafficInfoList() {
      return meshTrafficInfo_;
    }
    /**
     * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
     */
    public java.util.List<? extends com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfoOrBuilder> 
        getMeshTrafficInfoOrBuilderList() {
      return meshTrafficInfo_;
    }
    /**
     * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
     */
    public int getMeshTrafficInfoCount() {
      return meshTrafficInfo_.size();
    }
    /**
     * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
     */
    public com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo getMeshTrafficInfo(int index) {
      return meshTrafficInfo_.get(index);
    }
    /**
     * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
     */
    public com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfoOrBuilder getMeshTrafficInfoOrBuilder(
        int index) {
      return meshTrafficInfo_.get(index);
    }

    private void initFields() {
      head_ = "";
      meshTrafficInfo_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMeshTrafficInfoCount(); i++) {
        if (!getMeshTrafficInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHeadBytes());
      }
      for (int i = 0; i < meshTrafficInfo_.size(); i++) {
        output.writeMessage(2, meshTrafficInfo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHeadBytes());
      }
      for (int i = 0; i < meshTrafficInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, meshTrafficInfo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.evialab.the3rd.PlamgoRTTI.TrafficInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evialab.the3rd.PlamgoRTTI.TrafficInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evialab.the3rd.PlamgoRTTI.TrafficInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evialab.the3rd.PlamgoRTTI.TrafficInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evialab.the3rd.PlamgoRTTI.TrafficInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.evialab.the3rd.PlamgoRTTI.TrafficInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.evialab.the3rd.PlamgoRTTI.TrafficInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.evialab.the3rd.PlamgoRTTI.TrafficInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.evialab.the3rd.PlamgoRTTI.TrafficInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.evialab.the3rd.PlamgoRTTI.TrafficInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.evialab.the3rd.PlamgoRTTI.TrafficInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DTIPlus.TrafficInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DTIPlus.TrafficInfo)
        com.evialab.the3rd.PlamgoRTTI.TrafficInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.evialab.the3rd.PlamgoRTTI.internal_static_DTIPlus_TrafficInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.evialab.the3rd.PlamgoRTTI.internal_static_DTIPlus_TrafficInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.evialab.the3rd.PlamgoRTTI.TrafficInfo.class, com.evialab.the3rd.PlamgoRTTI.TrafficInfo.Builder.class);
      }

      // Construct using com.evialab.the3rd.PlamgoRTTI.TrafficInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMeshTrafficInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        head_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (meshTrafficInfoBuilder_ == null) {
          meshTrafficInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          meshTrafficInfoBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.evialab.the3rd.PlamgoRTTI.internal_static_DTIPlus_TrafficInfo_descriptor;
      }

      public com.evialab.the3rd.PlamgoRTTI.TrafficInfo getDefaultInstanceForType() {
        return com.evialab.the3rd.PlamgoRTTI.TrafficInfo.getDefaultInstance();
      }

      public com.evialab.the3rd.PlamgoRTTI.TrafficInfo build() {
        com.evialab.the3rd.PlamgoRTTI.TrafficInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.evialab.the3rd.PlamgoRTTI.TrafficInfo buildPartial() {
        com.evialab.the3rd.PlamgoRTTI.TrafficInfo result = new com.evialab.the3rd.PlamgoRTTI.TrafficInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.head_ = head_;
        if (meshTrafficInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            meshTrafficInfo_ = java.util.Collections.unmodifiableList(meshTrafficInfo_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.meshTrafficInfo_ = meshTrafficInfo_;
        } else {
          result.meshTrafficInfo_ = meshTrafficInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.evialab.the3rd.PlamgoRTTI.TrafficInfo) {
          return mergeFrom((com.evialab.the3rd.PlamgoRTTI.TrafficInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.evialab.the3rd.PlamgoRTTI.TrafficInfo other) {
        if (other == com.evialab.the3rd.PlamgoRTTI.TrafficInfo.getDefaultInstance()) return this;
        if (other.hasHead()) {
          bitField0_ |= 0x00000001;
          head_ = other.head_;
          onChanged();
        }
        if (meshTrafficInfoBuilder_ == null) {
          if (!other.meshTrafficInfo_.isEmpty()) {
            if (meshTrafficInfo_.isEmpty()) {
              meshTrafficInfo_ = other.meshTrafficInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMeshTrafficInfoIsMutable();
              meshTrafficInfo_.addAll(other.meshTrafficInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.meshTrafficInfo_.isEmpty()) {
            if (meshTrafficInfoBuilder_.isEmpty()) {
              meshTrafficInfoBuilder_.dispose();
              meshTrafficInfoBuilder_ = null;
              meshTrafficInfo_ = other.meshTrafficInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
              meshTrafficInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMeshTrafficInfoFieldBuilder() : null;
            } else {
              meshTrafficInfoBuilder_.addAllMessages(other.meshTrafficInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHead()) {
          
          return false;
        }
        for (int i = 0; i < getMeshTrafficInfoCount(); i++) {
          if (!getMeshTrafficInfo(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.evialab.the3rd.PlamgoRTTI.TrafficInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.evialab.the3rd.PlamgoRTTI.TrafficInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object head_ = "";
      /**
       * <code>required string head = 1;</code>
       *
       * <pre>
       * json字符�? type（rh/fcd）�?�version
       * </pre>
       */
      public boolean hasHead() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string head = 1;</code>
       *
       * <pre>
       * json字符�? type（rh/fcd）�?�version
       * </pre>
       */
      public java.lang.String getHead() {
        java.lang.Object ref = head_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            head_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string head = 1;</code>
       *
       * <pre>
       * json字符�? type（rh/fcd）�?�version
       * </pre>
       */
      public com.google.protobuf.ByteString
          getHeadBytes() {
        java.lang.Object ref = head_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          head_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string head = 1;</code>
       *
       * <pre>
       * json字符�? type（rh/fcd）�?�version
       * </pre>
       */
      public Builder setHead(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        head_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string head = 1;</code>
       *
       * <pre>
       * json字符�? type（rh/fcd）�?�version
       * </pre>
       */
      public Builder clearHead() {
        bitField0_ = (bitField0_ & ~0x00000001);
        head_ = getDefaultInstance().getHead();
        onChanged();
        return this;
      }
      /**
       * <code>required string head = 1;</code>
       *
       * <pre>
       * json字符�? type（rh/fcd）�?�version
       * </pre>
       */
      public Builder setHeadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        head_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo> meshTrafficInfo_ =
        java.util.Collections.emptyList();
      private void ensureMeshTrafficInfoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          meshTrafficInfo_ = new java.util.ArrayList<com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo>(meshTrafficInfo_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo, com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.Builder, com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfoOrBuilder> meshTrafficInfoBuilder_;

      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public java.util.List<com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo> getMeshTrafficInfoList() {
        if (meshTrafficInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(meshTrafficInfo_);
        } else {
          return meshTrafficInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public int getMeshTrafficInfoCount() {
        if (meshTrafficInfoBuilder_ == null) {
          return meshTrafficInfo_.size();
        } else {
          return meshTrafficInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo getMeshTrafficInfo(int index) {
        if (meshTrafficInfoBuilder_ == null) {
          return meshTrafficInfo_.get(index);
        } else {
          return meshTrafficInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public Builder setMeshTrafficInfo(
          int index, com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo value) {
        if (meshTrafficInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeshTrafficInfoIsMutable();
          meshTrafficInfo_.set(index, value);
          onChanged();
        } else {
          meshTrafficInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public Builder setMeshTrafficInfo(
          int index, com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.Builder builderForValue) {
        if (meshTrafficInfoBuilder_ == null) {
          ensureMeshTrafficInfoIsMutable();
          meshTrafficInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          meshTrafficInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public Builder addMeshTrafficInfo(com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo value) {
        if (meshTrafficInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeshTrafficInfoIsMutable();
          meshTrafficInfo_.add(value);
          onChanged();
        } else {
          meshTrafficInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public Builder addMeshTrafficInfo(
          int index, com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo value) {
        if (meshTrafficInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeshTrafficInfoIsMutable();
          meshTrafficInfo_.add(index, value);
          onChanged();
        } else {
          meshTrafficInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public Builder addMeshTrafficInfo(
          com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.Builder builderForValue) {
        if (meshTrafficInfoBuilder_ == null) {
          ensureMeshTrafficInfoIsMutable();
          meshTrafficInfo_.add(builderForValue.build());
          onChanged();
        } else {
          meshTrafficInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public Builder addMeshTrafficInfo(
          int index, com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.Builder builderForValue) {
        if (meshTrafficInfoBuilder_ == null) {
          ensureMeshTrafficInfoIsMutable();
          meshTrafficInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          meshTrafficInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public Builder addAllMeshTrafficInfo(
          java.lang.Iterable<? extends com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo> values) {
        if (meshTrafficInfoBuilder_ == null) {
          ensureMeshTrafficInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, meshTrafficInfo_);
          onChanged();
        } else {
          meshTrafficInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public Builder clearMeshTrafficInfo() {
        if (meshTrafficInfoBuilder_ == null) {
          meshTrafficInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          meshTrafficInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public Builder removeMeshTrafficInfo(int index) {
        if (meshTrafficInfoBuilder_ == null) {
          ensureMeshTrafficInfoIsMutable();
          meshTrafficInfo_.remove(index);
          onChanged();
        } else {
          meshTrafficInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.Builder getMeshTrafficInfoBuilder(
          int index) {
        return getMeshTrafficInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfoOrBuilder getMeshTrafficInfoOrBuilder(
          int index) {
        if (meshTrafficInfoBuilder_ == null) {
          return meshTrafficInfo_.get(index);  } else {
          return meshTrafficInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public java.util.List<? extends com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfoOrBuilder> 
           getMeshTrafficInfoOrBuilderList() {
        if (meshTrafficInfoBuilder_ != null) {
          return meshTrafficInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(meshTrafficInfo_);
        }
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.Builder addMeshTrafficInfoBuilder() {
        return getMeshTrafficInfoFieldBuilder().addBuilder(
            com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.Builder addMeshTrafficInfoBuilder(
          int index) {
        return getMeshTrafficInfoFieldBuilder().addBuilder(
            index, com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .DTIPlus.MeshTrafficInfo meshTrafficInfo = 2;</code>
       */
      public java.util.List<com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.Builder> 
           getMeshTrafficInfoBuilderList() {
        return getMeshTrafficInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo, com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.Builder, com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfoOrBuilder> 
          getMeshTrafficInfoFieldBuilder() {
        if (meshTrafficInfoBuilder_ == null) {
          meshTrafficInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo, com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfo.Builder, com.evialab.the3rd.PlamgoRTTI.MeshTrafficInfoOrBuilder>(
                  meshTrafficInfo_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          meshTrafficInfo_ = null;
        }
        return meshTrafficInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:DTIPlus.TrafficInfo)
    }

    static {
      defaultInstance = new TrafficInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DTIPlus.TrafficInfo)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DTIPlus_LinkTrafficInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DTIPlus_LinkTrafficInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DTIPlus_MeshTrafficInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DTIPlus_MeshTrafficInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DTIPlus_TrafficInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DTIPlus_TrafficInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016plamgortti.txt\022\007DTIPlus\"6\n\017LinkTraffic" +
      "Info\022\016\n\006linkid\030\001 \002(\005\022\023\n\013trafficInfo\030\002 \002(" +
      "\005\"T\n\017MeshTrafficInfo\022\016\n\006meshid\030\001 \002(\005\0221\n\017" +
      "linkTrafficInfo\030\002 \003(\0132\030.DTIPlus.LinkTraf" +
      "ficInfo\"N\n\013TrafficInfo\022\014\n\004head\030\001 \002(\t\0221\n\017" +
      "meshTrafficInfo\030\002 \003(\0132\030.DTIPlus.MeshTraf" +
      "ficInfoB \n\022com.evialab.the3rdB\nPlamgoRTT" +
      "I"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DTIPlus_LinkTrafficInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DTIPlus_LinkTrafficInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DTIPlus_LinkTrafficInfo_descriptor,
        new java.lang.String[] { "Linkid", "TrafficInfo", });
    internal_static_DTIPlus_MeshTrafficInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DTIPlus_MeshTrafficInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DTIPlus_MeshTrafficInfo_descriptor,
        new java.lang.String[] { "Meshid", "LinkTrafficInfo", });
    internal_static_DTIPlus_TrafficInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DTIPlus_TrafficInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DTIPlus_TrafficInfo_descriptor,
        new java.lang.String[] { "Head", "MeshTrafficInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
